# Generated by Django 3.2.9 on 2021-11-25 20:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_auto_20211120_1645'),
    ]

    operations = [
        migrations.RenameField(
            model_name='post',
            old_name='post_image',
            new_name='posts',
        ),
    ]
