# Generated by Django 3.2.9 on 2021-11-25 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_rename_post_image_post_posts'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Tag',
        ),
        migrations.AlterField(
            model_name='post',
            name='posts',
            field=models.ImageField(upload_to='images/'),
        ),
    ]
